Models/Livro.cs
using System.ComponentModel.DataAnnotations;

namespace MVCBiblioteca.Models
{
    public class Livro
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "O título é obrigatório")]
        [Display(Name = "Título")]
        public string Titulo { get; set; }
        [Required(ErrorMessage = "O autor é obrigatório")]
        public string Autor { get; set; }
        [Required(ErrorMessage = "A descrição é obrigatório")]
        [Display(Name ="Descrição")]
        public string Descricao { get; set; }
        [Required(ErrorMessage = "O ano da publicação é obrigatório")]
        [Display(Name ="Ano da Publicação")]
        public string AnoPublicacao { get; set; }
        public string Editora { get; set; }
        [Display(Name ="ISBN")]
        public string Isbn { get; set; }
        [Required(ErrorMessage = "A capa é obrigatório")]
        [Display(Name ="Capa")]
        public string Capa { get; set; }
        [Required(ErrorMessage = "O genero é obrigatório")]
        [Display(Name ="Gênero")]
        public string Genero { get; set; }
        [Required(ErrorMessage = "A quantidade é obrigatório")]
        [Display(Name ="Quantidade em estoque")]
        public int QuantidadeEstoque { get; set; }
    }
}

Controllers/EmprestimosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCBiblioteca.Data;
using MVCBiblioteca.Models;

namespace MVCBiblioteca.Controllers
{
    public class EmprestimosController : Controller
    {
        private readonly BibliotecaContext _context;

        public EmprestimosController(BibliotecaContext context)
        {
            _context = context;
        }

        // GET: Emprestimos
        public async Task<IActionResult> Index()
        {
            var context = await _context.Emprestimo.Include(e => e.Livro).Include(e => e.Usuario).ToListAsync();
            return View(context);
        }

        // GET: Emprestimos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emprestimo = await _context.Emprestimo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        // GET: Emprestimos/Create
        public IActionResult Create()
        {
            ViewBag.livros = new SelectList(_context.Livro, "Id", "Titulo");
            ViewBag.usuarios = new SelectList(_context.Usuario, "Id", "Nome");
            return View();
        }

        // POST: Emprestimos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,LivroId,UsuarioId,DataEmprestimo,DataDevolucao")] Emprestimo emprestimo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(emprestimo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(emprestimo);
        }

        // GET: Emprestimos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emprestimo = await _context.Emprestimo.FindAsync(id);
            if (emprestimo == null)
            {
                return NotFound();
            }
            ViewBag.livros = new SelectList(_context.Livro, "Id", "Titulo");
            ViewBag.usuarios = new SelectList(_context.Usuario, "Id", "Nome");
            return View(emprestimo);
        }

        // POST: Emprestimos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,LivroId,UsuarioId,DataEmprestimo,DataDevolucao")] Emprestimo emprestimo)
        {
            if (id != emprestimo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(emprestimo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmprestimoExists(emprestimo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(emprestimo);
        }

        // GET: Emprestimos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emprestimo = await _context.Emprestimo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        // POST: Emprestimos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var emprestimo = await _context.Emprestimo.FindAsync(id);
            if (emprestimo != null)
            {
                _context.Emprestimo.Remove(emprestimo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmprestimoExists(int id)
        {
            return _context.Emprestimo.Any(e => e.Id == id);
        }
    }
}

Controllers/LivrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCBiblioteca.Data;
using MVCBiblioteca.Models;

namespace MVCBiblioteca.Controllers
{
    public class LivrosController : Controller
    {
        private readonly BibliotecaContext _context;

        public LivrosController(BibliotecaContext context)
        {
            _context = context;
        }

        // GET: Livros
        public async Task<IActionResult> Index()
        {
            return View(await _context.Livro.ToListAsync());
        }

        // GET: Livros/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livro
                .FirstOrDefaultAsync(m => m.Id == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        // GET: Livros/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Livros/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Autor,AnoPublicacao,Editora,Isbn,Genero,QuantidadeEstoque,Descricao,Capa")] Livro livro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(livro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(livro);
        }

        // GET: Livros/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livro.FindAsync(id);
            if (livro == null)
            {
                return NotFound();
            }
            return View(livro);
        }

        // POST: Livros/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,Autor,AnoPublicacao,Editora,Isbn,Genero,QuantidadeEstoque,Capa,Descricao")] Livro livro)
        {
            if (id != livro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(livro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LivroExists(livro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(livro);
        }

        // GET: Livros/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livro
                .FirstOrDefaultAsync(m => m.Id == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        // POST: Livros/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var livro = await _context.Livro.FindAsync(id);
            if (livro != null)
            {
                _context.Livro.Remove(livro);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LivroExists(int id)
        {
            return _context.Livro.Any(e => e.Id == id);
        }
    }
}

Views/Livros/Create.cshtml
@model MVCBiblioteca.Models.Livro

@{
    ViewData["Title"] = "Create";
}

<h1>Inserir um novo Livro</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnoPublicacao" class="control-label"></label>
                <input asp-for="AnoPublicacao" class="form-control" />
                <span asp-validation-for="AnoPublicacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Editora" class="control-label"></label>
                <input asp-for="Editora" class="form-control" />
                <span asp-validation-for="Editora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Isbn" class="control-label"></label>
                <input asp-for="Isbn" class="form-control" />
                <span asp-validation-for="Isbn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>  <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>  <div class="form-group">
                <label asp-for="Capa" class="control-label"></label>
                <input asp-for="Capa" class="form-control" />
                <span asp-validation-for="Capa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantidadeEstoque" class="control-label"></label>
                <input asp-for="QuantidadeEstoque" class="form-control" />
                <span asp-validation-for="QuantidadeEstoque" class="text-danger"></span>
            </div>
            <div class="form-group d-inline-flex mt-2">
            </div>
        </form>
                <a asp-action="Index" class="btn btn-primary">Voltar para a lista</a>
                <input type="submit" value="Criar" class="btn btn-success ml-2" />
    </div>
</div>

<div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Livros/Delete.cshtml
@model MVCBiblioteca.Models.Livro

@{
    ViewData["Title"] = "Excluir";
}

<h1>Excluir livro</h1>

<h3>Tem certeza que deseja excluir esse livro?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnoPublicacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnoPublicacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Editora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Editora)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Isbn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Isbn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuantidadeEstoque)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuantidadeEstoque)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <a asp-action="Index" class="btn btn-primary">Voltar</a>
        <input type="submit" value="Excluir" class="btn btn-danger" /> 
    </form>
</div>

Views/Livros/Details.cshtml
@model MVCBiblioteca.Models.Livro

@{
    ViewData["Title"] = "Details";
}
<div class="row">
    <div class="col-md-4 ">
        <img src="@Model.Capa" class="img-fluid h-100" alt="Alternate Text" />
    </div>
    <div class="col-md-8">
        <h1>Detalhes</h1>

        <div class="align-text-botton">
            <h4>@Html.DisplayNameFor(model => Model.QuantidadeEstoque)</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Titulo)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Titulo)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Autor)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Autor)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.AnoPublicacao)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.AnoPublicacao)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Editora)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Editora)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Isbn)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Isbn)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Genero)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Genero)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.QuantidadeEstoque)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.QuantidadeEstoque)
                </dd>
            </dl>
        </div>
        <div>
            <a asp-action="Index" class="btn btn-primary">Voltar</a>
            <a asp-action="Create" asp-controller="Emprestimos" class="btn btn-primary">Novo Emprestimo</a> 
            <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-success">Editar</a> 
            <a asp-action="Delete" asp-route-id="@Model?.Id" class="btn btn-danger">Excluir</a>
        </div>
    </div>

</div>

Views/Livros/Edit.cshtml
@model MVCBiblioteca.Models.Livro

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar livro</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnoPublicacao" class="control-label"></label>
                <input asp-for="AnoPublicacao" class="form-control" />
                <span asp-validation-for="AnoPublicacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Editora" class="control-label"></label>
                <input asp-for="Editora" class="form-control" />
                <span asp-validation-for="Editora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Isbn" class="control-label"></label>
                <input asp-for="Isbn" class="form-control" />
                <span asp-validation-for="Isbn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div> <div class="form-group">
                <label asp-for="Capa" class="control-label"></label>
                <input asp-for="Capa" class="form-control" />
                <span asp-validation-for="Capa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantidadeEstoque" class="control-label"></label>
                <input asp-for="QuantidadeEstoque" class="form-control" />
                <span asp-validation-for="QuantidadeEstoque" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <a asp-action="Index" class="btn btn-primary">Voltar</a>
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Livros/Index.cshtml
@model IEnumerable<MVCBiblioteca.Models.Livro>

@{
    ViewData["Title"] = "Livros";
}
<div class="container mb-3">
<h1>Livros</h1>
    <a asp-action="Create" class="btn btn-primary">Inserir livro</a>

</div>


<div class="container">
    <div class="row-cols-lg-4 row">
        @foreach (var item in Model)
        {
            <div class="card mb-2" style="width: 16rem; margin-left: 10px">
                <img src="@item.Capa" class="card-img-top rounded card-img-top align-self-center mt-1" alt="..." style="height:15rem; width:fit-content">
                <div class="card-body">
                    <h5 class="card-title">@item.Titulo</h5>
                    <p class="card-text">@item.Descricao</p>
                </div>
                    <a  class="btn btn-primary mb-1" asp-action="Details" asp-route-id="@item.Id">Saiba mais</a>
            </div>
        }

    </div>
</div>